[WIP]Implement asynchronous communication
takuan1108/chat-space pull request #8
Opened 2019-02-22 07:04 UTC by takuan1108

2019-02-23 12:32 UTC, takuan1108 commented
![feb-23-2019 20-57-39](https://user-images.githubusercontent.com/44314408/53286475-69307300-37b2-11e9-8b85-a29e43fb4847.gif)
コメント機能の非同期通信終わりましたので確認お願いします！

2019-02-23 12:43 UTC, yuki-uchida requested changes

2019-02-23 12:43 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function buildHtml(message){
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-02-23 12:43 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .done(function(data){
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-02-23 12:50 UTC, takuan1108 commented on app/assets/javascripts/message.js
> +  function buildHtml(message){
確かに！変更してみます！

2019-02-23 12:51 UTC, takuan1108 commented on app/assets/javascripts/message.js
> +    .done(function(data){
了解しました！

2019-02-24 01:52 UTC, yuki-uchida commented
LGTMです

2019-02-24 07:53 UTC, merged